# Build script for FreeType

before_script:
  - export CFLAGS="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security"
  - export CPPFLAGS="-D_FORTIFY_SOURCE=2"
  - export CXXFLAGS="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security"
  - export FCFLAGS="-g -O2 -fstack-protector-strong"
  - export FFLAGS="-g -O2 -fstack-protector-strong"
  - export GCJFLAGS="-g -O2 -fstack-protector-strong"
  - export LDFLAGS="-Wl,-z,relro"
  - export OBJCFLAGS="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security"
  - export OBJCXXFLAGS="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security"
  #- sudo apt-get build-dep freetype
  - rm -rf ./lipkg/target
  - find $BUILDROOT/lipkg/ -name "*.ipk*" -exec rm {} \;

script:
  - |
    ./configure --prefix=/app
  - make -j2
  - make install DESTDIR=$BUILDROOT/lipkg/target/
  # remove cruft
  - find $BUILDROOT/lipkg/target/ -name "*.la" -exec rm -rf {} \;
  - find $BUILDROOT/lipkg/target/ -name "*.a" -exec rm -rf {} \;
  # build package
  - lipkgen build lipkg/ --no-signature

after_script:
  - make clean distclean
