# Build script for SDL-2

before_script:
  - export CFLAGS="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security"
  - export CPPFLAGS="-D_FORTIFY_SOURCE=2"
  - export CXXFLAGS="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security"
  - export FCFLAGS="-g -O2 -fstack-protector-strong"
  - export FFLAGS="-g -O2 -fstack-protector-strong"
  - export GCJFLAGS="-g -O2 -fstack-protector-strong"
  - export LDFLAGS="-Wl,-z,relro"
  - export OBJCFLAGS="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security"
  - export OBJCXXFLAGS="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security"
  #- sudo apt-get build-dep libsdl2
  - rm -rf $BUILDROOT/lipkg/target
  - find $BUILDROOT/lipkg/ -name "*.ipk*" -exec rm {} \;

script:
  # SDL2
  - cd SDL2
  - |
    ./configure --prefix=/app \
            --disable-rpath --enable-sdl-dlopen --disable-loadso \
            --disable-nas --disable-esd --disable-arts \
            --disable-alsa-shared --disable-pulseaudio-shared \
            --disable-x11-shared --disable-video-directfb \
            --enable-video-opengles \
            --enable-video-wayland --disable-wayland-shared
  - make -j4
  - make install DESTDIR=$BUILDROOT/lipkg/target/
  - sudo make install
  - cd ..
  # SDL2-ttf
  - cd SDL2-ttf
  - ./autogen.sh
  - ./configure --prefix=/app
  - make -j4
  - make install DESTDIR=$BUILDROOT/lipkg/target/
  - cd ..
  # remove cruft
  - find $BUILDROOT/lipkg/target/ -name "*.la" -exec rm -rf {} \;
  - find $BUILDROOT/lipkg/target/ -name "*.a" -exec rm -rf {} \;
  # build package
  - lipkgen build lipkg/ --no-signature

after_script:
  - cd SDL2
  - make clean distclean
  - cd ..
  - cd SDL2-ttf
  - make clean distclean
  - cd ..
