# Build script for Neverball

before_script:
  - export CFLAGS="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security"
  - export CPPFLAGS="-D_FORTIFY_SOURCE=2 -DNDEBUG"
  - export CXXFLAGS="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security"
  - export FCFLAGS="-g -O2 -fstack-protector-strong"
  - export FFLAGS="-g -O2 -fstack-protector-strong"
  - export GCJFLAGS="-g -O2 -fstack-protector-strong"
  - export LDFLAGS="-Wl,-z,relro"
  - export OBJCFLAGS="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security"
  - export OBJCXXFLAGS="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security"
  - env | sort
  #- sudo apt-get build-dep neverball
  - rm -rf $BUILDROOT/lipkg/target
  - find $BUILDROOT/lipkg/ -name "*.ipk*" -exec rm {} \;

script:

  - make DATADIR=/app/neverball LOCALEDIR=/app/share/locale -j4
  #- make install DESTDIR=./lipkg/target/
  - install -d ./lipkg/target/neverball
  - install -d ./lipkg/target/bin
  - install -d ./lipkg/target/share/applications
  - install -d ./lipkg/target/share/icons/hicolor/128x128/apps
  - cp      -dpr data/*              ./lipkg/target/neverball/
  - cp      -dpr locale/             ./lipkg/target/share/
  - install dist/neverball.desktop   ./lipkg/target/share/applications
  - cp dist/neverball_128.png        ./lipkg/target/share/icons/hicolor/128x128/apps/neverball.png
  - install mapc                     ./lipkg/target/bin
  - install neverball                ./lipkg/target/bin
  - chmod -R 755 ./lipkg/target/neverball/ # we need to fixup permissions...
  - lipkgen build lipkg/ --no-signature

after_script:
  - make clean
