# Build script for libjpeg-turbo

before_script:
  - export CFLAGS="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security"
  - export CPPFLAGS="-D_FORTIFY_SOURCE=2"
  - export CXXFLAGS="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security"
  - export FCFLAGS="-g -O2 -fstack-protector-strong"
  - export FFLAGS="-g -O2 -fstack-protector-strong"
  - export GCJFLAGS="-g -O2 -fstack-protector-strong"
  - export LDFLAGS="-Wl,-z,relro"
  - export OBJCFLAGS="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security"
  - export OBJCXXFLAGS="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security"
  #- sudo apt-get build-dep libjpeg-turbo
  - "[ -d ./lipkg/inst_target ] && rm -r ./lipkg/inst_target"

script:
  - ./configure --prefix=/opt/bundle
  - make -j4
  - make install DESTDIR=$CURDIR/lipkg/inst_target/
  # remove cruft
  - find $CURDIR/lipkg/inst_target/ -name "*.la" -exec rm -rf {} \;
  - find $CURDIR/lipkg/inst_target/ -name "*.a" -exec rm -rf {} \;
  # we don't want to ship the executables
  - rm -r $CURDIR/lipkg/inst_target/opt/bundle/bin
  # build package
  - lipkgen build lipkg/

after_script:
  - make clean distclean
